
% function [A, B] = my_weighted_linear_fit(MSDs)
for i = 1:length(MSDs)
delta_var = (sum(MSDs(i).weights)*...
    dot(MSDs(i).weights,MSDs(i).MSD(:,1).^2)-...
    dot(MSDs(i).weights,MSDs(i).MSD(:,1))^2);
A(i) = (dot(MSDs(i).weights,MSDs(i).MSD(:,1).^2)*...
    dot(MSDs(i).weights,MSDs(i).MSD(:,2)) - ...
    dot(MSDs(i).weights,MSDs(i).MSD(:,1))*...
    dot(MSDs(i).weights,MSDs(i).MSD(:,1).*MSDs(i).MSD(:,2)))/...
    delta_var;
B(i) = (sum(MSDs(i).weights)*...
    dot(MSDs(i).weights,MSDs(i).MSD(:,1).*MSDs(i).MSD(:,2))-...
    dot(MSDs(i).weights,MSDs(i).MSD(:,1))*...
    dot(MSDs(i).weights,MSDs(i).MSD(:,2)))/...
    delta_var;
end
% end